#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

REPO='simnalamburt/github-ff-merge-test'
BRANCH='main'

# 현재 main 확인
curl --fail-with-body -sS -L \
  -H 'Accept: application/vnd.github+json' \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H 'X-GitHub-Api-Version: 2022-11-28' \
  "https://api.github.com/repos/${REPO}/git/ref/heads/${BRANCH}"
