#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

REPO='simnalamburt/github-ff-merge-test'
BRANCH='main'
TARGET='97c5418dbc54aae4caf386f6831eea49b6cc180a'

# fast-forward merge BRANCH to TARGET
curl --fail-with-body -sS -L \
  -X PATCH \
  -H 'Accept: application/vnd.github+json' \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H 'X-GitHub-Api-Version: 2022-11-28' \
  "https://api.github.com/repos/${REPO}/git/refs/heads/${BRANCH}" \
  -d "{\"sha\":\"${TARGET}\",\"force\":false}"
